[package]
name = "libsignal-service-actix"
version = "0.1.0"
authors = ["Ruben De Smet <ruben.de.smet@rubdos.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsignal-service = { path = "../libsignal-service" }
libsignal-protocol = { git = "https://github.com/kunerd/libsignal-protocol-rs", branch = "enable_feature_const_if_match" }

awc = { version = "3.0.0-beta.1", features=["rustls"] }
actix = "0.11.0-beta.1"
actix-http = "3.0.0-beta.1"
actix-rt = "2.0.0-beta.1"
mpart-async = "0.5.0"
serde_json = "1.0"
futures = "0.3"
bytes = "1"
rustls = "0.19"
url = "2.1"
serde = "1.0"
log = "0.4"
rand = "0.8"

failure = "0.1.5"
thiserror = "1.0"
async-trait = "0.1.30"
base64 = "0.13"

[dev-dependencies]
env_logger = "0.8"
image = { version = "0.23", default-features = false, features = ["png"] }
opener = "0.4"
qrcode = "0.12"
rand = "0.8"
structopt = "0.3"
tokio = { version = "1", features=["macros"] }
