[package]
name = "libsignal-service"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>", "Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"
license = "GPLv3"
readme = "../README.md"

[dependencies]
libsignal-protocol = { git = "https://github.com/kunerd/libsignal-protocol-rs", branch="enable_feature_const_if_match" }
async-trait = "0.1.30"
url = { version = "2.1.1", features = ["serde"] }
base64 = "0.13"
bytes = "1"
futures = "0.3"
pin-project = "1.0"
thiserror = "1.0"
serde = {version = "1.0", features=["derive"]}
prost = "0.7"
http = "0.2.2"
chrono = { version = "0.4", features = ["serde"] }
log = "0.4.8"

sha2 = "0.9.0"
hmac = "0.10.0"
aes = "0.6.0"
aes-gcm = "0.8.0"
aes-ctr = "0.6.0"
block-modes = "0.7.0"
rand = "0.8.0"

[build-dependencies]
prost-build = "0.7"

[dev-dependencies]
anyhow = "1.0"

[features]
prefer-e164 = []
